"""Coloquei 'autoincrement=True' nos id's

Revision ID: 59b3b6c8f735
Revises: bd4449a11778
Create Date: 2026-08-12 16:54:49.558630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59b3b6c8f735'
down_revision: Union[str, Sequence[str], None] = 'bd4449a11778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
