"""Corrigi a coluna 'bloqueado_ate' dentro da tabela TentativaLogin e 'data_fim' de Assinatura

Revision ID: 783160813ad2
Revises: 1931699a0246
Create Date: 2026-08-12 18:45:47.586216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '783160813ad2'
down_revision: Union[str, Sequence[str], None] = '1931699a0246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assinatura', 'data_fim',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assinatura', 'data_fim',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
