"""Pus duas classes novas no models

Revision ID: bd4449a11778
Revises: e947197c1359
Create Date: 2026-08-10 17:10:37.604207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd4449a11778'
down_revision: Union[str, Sequence[str], None] = 'e947197c1359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assinatura', sa.Column('dia_cobranca', sa.Integer(), nullable=False))
    op.alter_column('assinatura', 'data_inicio',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('planos', 'valor_plano',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('transacao', 'valor_pagamento',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transacao', 'valor_pagamento',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=False)
    op.alter_column('planos', 'valor_plano',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=False)
    op.alter_column('assinatura', 'data_inicio',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('assinatura', 'dia_cobranca')
    # ### end Alembic commands ###
