"""Initial Migration

Revision ID: e947197c1359
Revises: 
Create Date: 2026-08-08 15:24:39.751292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e947197c1359'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_plano', sa.Enum('BASICO', 'PREMIUM', name='enumplano'), nullable=False),
    sa.Column('valor_plano', sa.DECIMAL(precision=4, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planos_id'), 'planos', ['id'], unique=False)
    op.create_table('tentativas_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tentativas', sa.Integer(), nullable=True),
    sa.Column('bloqueado_ate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tentativas_login_id'), 'tentativas_login', ['id'], unique=False)
    op.create_index(op.f('ix_tentativas_login_usuario_id'), 'tentativas_login', ['usuario_id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nome_usuario', sa.String(length=150), nullable=False),
    sa.Column('senha', sa.String(length=225), nullable=False),
    sa.Column('cpf', sa.CHAR(length=11), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('telefone', sa.String(length=16), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_table('assinatura',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('status_assinatura', sa.Enum('ATIVO', 'CANCELADO', name='enumassinatura'), nullable=False),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assinatura_id'), 'assinatura', ['id'], unique=False)
    op.create_table('refresh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('expira_em', sa.DateTime(), nullable=True),
    sa.Column('ativo_token', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_id'), 'refresh', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_token'), 'refresh', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_usuario_id'), 'refresh', ['usuario_id'], unique=False)
    op.create_table('transacao',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('assinatura_id', sa.BigInteger(), nullable=False),
    sa.Column('status_transacao', sa.Enum('APROVADO', 'PENDENTE', 'CANCELADO', name='enumtransacao'), nullable=False),
    sa.Column('valor_pagamento', sa.DECIMAL(precision=4, scale=2), nullable=False),
    sa.Column('metodo_pagamento', sa.Enum('CREDITO', 'DEBITO', 'PIX', name='enumpagamento'), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['assinatura_id'], ['assinatura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacao_id'), 'transacao', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transacao_id'), table_name='transacao')
    op.drop_table('transacao')
    op.drop_index(op.f('ix_refresh_usuario_id'), table_name='refresh')
    op.drop_index(op.f('ix_refresh_token'), table_name='refresh')
    op.drop_index(op.f('ix_refresh_id'), table_name='refresh')
    op.drop_table('refresh')
    op.drop_index(op.f('ix_assinatura_id'), table_name='assinatura')
    op.drop_table('assinatura')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_tentativas_login_usuario_id'), table_name='tentativas_login')
    op.drop_index(op.f('ix_tentativas_login_id'), table_name='tentativas_login')
    op.drop_table('tentativas_login')
    op.drop_index(op.f('ix_planos_id'), table_name='planos')
    op.drop_table('planos')
    # ### end Alembic commands ###
